## 데이터 불러오기

In [22]:
import pandas as pd
#데이터 로드
X_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/x_train.csv")
y_train = pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/y_train.csv")
X_test= pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/muscle/x_test.csv")


display(X_train.head())
display(y_train.head())

,ID,motion_0,motion_1,motion_2,motion_3,motion_4,motion_5,motion_6,motion_7,motion_8,...,motion_54,motion_55,motion_56,motion_57,motion_58,motion_59,motion_60,motion_61,motion_62,motion_63
0,0,1.0,-2.0,-1.0,4.0,-5.0,-4.0,1.0,0.0,-15.0,...,0.0,-1.0,-13.0,-3.0,1.0,-1.0,-32.0,-22.0,-2.0,-3.0
1,2,20.0,0.0,0.0,1.0,5.0,6.0,-52.0,18.0,15.0,...,-70.0,-55.0,-38.0,-14.0,-12.0,-8.0,-34.0,-63.0,-87.0,-77.0
2,4,1.0,-1.0,1.0,4.0,-5.0,-8.0,1.0,-3.0,-14.0,...,1.0,12.0,-25.0,0.0,0.0,3.0,2.0,-27.0,1.0,0.0
3,5,13.0,2.0,1.0,-3.0,1.0,3.0,28.0,3.0,12.0,...,0.0,-21.0,-17.0,-2.0,0.0,-4.0,-17.0,-21.0,-21.0,25.0
4,6,-2.0,-7.0,-4.0,-8.0,16.0,44.0,1.0,3.0,-16.0,...,-1.0,2.0,-1.0,1.0,4.0,4.0,-17.0,-38.0,-3.0,3.0

   ID  pose
0   0     1
1   2     0
2   4     1
3   5     0
4   6     1

## EDA

### shape

### info

In [23]:
print(X_train.info())
print("-"*80)
print(X_test.info())
print("-"*80)
print(y_train.info())
print("-"*80)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         4650 non-null   int64
 1   motion_0   4650 non-null   float64
 2   motion_1   4650 non-null   float64
 3   motion_2   4650 non-null   float64
 4   motion_3   4650 non-null   float64
 5   motion_4   4650 non-null   float64
 6   motion_5   4650 non-null   float64
 7   motion_6   4650 non-null   float64
 8   motion_7   4650 non-null   float64
 9   motion_8   4650 non-null   float64
 10  motion_9   4650 non-null   float64
 11  motion_10  4650 non-null   float64
 12  motion_11  4650 non-null   float64
 13  motion_12  4650 non-null   float64
 14  motion_13  4650 non-null   float64
 15  motion_14  4650 non-null   float64
 16  motion_15  4650 non-null   float64
 17  motion_16  4650 non-null   float64
 18  motion_17  4650 non-null   float64
 19  motion_18  4650 non-null   float64
 20  motion_19  4650 non-null   float64
 21  motion_20  4650 non-null   float64
 22  motion_21  4650 non-null   float64
 23  motion_22  4650 non-null   float64
 24  motion_23  4650 non-null   float64
 25  motion_24  4650 non-null   float64
 26  motion_25  4650 non-null   float64
 27  motion_26  4650 non-null   float64
 28  motion_27  4650 non-null   float64
 29  motion_28  4650 non-null   float64
 30  motion_29  4650 non-null   float64
 31  motion_30  4650 non-null   float64
 32  motion_31  4650 non-null   float64
 33  motion_32  4650 non-null   float64
 34  motion_33  4650 non-null   float64
 35  motion_34  4650 non-null   float64
 36  motion_35  4650 non-null   float64
 37  motion_36  4650 non-null   float64
 38  motion_37  4650 non-null   float64
 39  motion_38  4650 non-null   float64
 40  motion_39  4650 non-null   float64
 41  motion_40  4650 non-null   float64
 42  motion_41  4650 non-null   float64
 43  motion_42  4650 non-null   float64
 44  motion_43  4650 non-null   float64
 45  motion_44  4650 non-null   float64
 46  motion_45  4650 non-null   float64
 47  motion_46  4650 non-null   float64
 48  motion_47  4650 non-null   float64
 49  motion_48  4650 non-null   float64
 50  motion_49  4650 non-null   float64
 51  motion_50  4650 non-null   float64
 52  motion_51  4650 non-null   float64
 53  motion_52  4650 non-null   float64
 54  motion_53  4650 non-null   float64
 55  motion_54  4650 non-null   float64
 56  motion_55  4650 non-null   float64
 57  motion_56  4650 non-null   float64
 58  motion_57  4650 non-null   float64
 59  motion_58  4650 non-null   float64
 60  motion_59  4650 non-null   float64
 61  motion_60  4650 non-null   float64
 62  motion_61  4650 non-null   float64
 63  motion_62  4650 non-null   float64
 64  motion_63  4650 non-null   float64
dtypes: float64(64), int64(1)
memory usage: 2.3 MB
None
--------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1163 entries, 0 to 1162
Data columns (total 65 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1163 non-null   int64
 1   motion_0   1163 non-null   float64
 2   motion_1   1163 non-null   float64
 3   motion_2   1163 non-null   float64
 4   motion_3   1163 non-null   float64
 5   motion_4   1163 non-null   float64
 6   motion_5   1163 non-null   float64
 7   motion_6   1163 non-null   float64
 8   motion_7   1163 non-null   float64
 9   motion_8   1163 non-null   float64
 10  motion_9   1163 non-null   float64
 11  motion_10  1163 non-null   float64
 12  motion_11  1163 non-null   float64
 13  motion_12  1163 non-null   float64
 14  motion_13  1163 non-null   float64
 15  motion_14  1163 non-null   float64
 16  motion_15  1163 non-null   float64
 17  motion_16  1163 non-null   float64
 18  motion_17  1163 non-null   float64
 19  motion_18  1163 non-null   float64
 20  motion_19  1163 non-null   float64
 21  motion_20  1163 non-null   float64
 22  motion_21  1163 non-null   float64
 23  motion_22  1163 non-null   float64
 24  motion_23  1163 non-null   float64
 25  motion_24  1163 non-null   float64
 26  motion_25  1163 non-null   float64
 27  motion_26  1163 non-null   float64
 28  motion_27  1163 non-null   float64
 29  motion_28  1163 non-null   float64
 30  motion_29  1163 non-null   float64
 31  motion_30  1163 non-null   float64
 32  motion_31  1163 non-null   float64
 33  motion_32  1163 non-null   float64
 34  motion_33  1163 non-null   float64
 35  motion_34  1163 non-null   float64
 36  motion_35  1163 non-null   float64
 37  motion_36  1163 non-null   float64
 38  motion_37  1163 non-null   float64
 39  motion_38  1163 non-null   float64
 40  motion_39  1163 non-null   float64
 41  motion_40  1163 non-null   float64
 42  motion_41  1163 non-null   float64
 43  motion_42  1163 non-null   float64
 44  motion_43  1163 non-null   float64
 45  motion_44  1163 non-null   float64
 46  motion_45  1163 non-null   float64
 47  motion_46  1163 non-null   float64
 48  motion_47  1163 non-null   float64
 49  motion_48  1163 non-null   float64
 50  motion_49  1163 non-null   float64
 51  motion_50  1163 non-null   float64
 52  motion_51  1163 non-null   float64
 53  motion_52  1163 non-null   float64
 54  motion_53  1163 non-null   float64
 55  motion_54  1163 non-null   float64
 56  motion_55  1163 non-null   float64
 57  motion_56  1163 non-null   float64
 58  motion_57  1163 non-null   float64
 59  motion_58  1163 non-null   float64
 60  motion_59  1163 non-null   float64
 61  motion_60  1163 non-null   float64
 62  motion_61  1163 non-null   float64
 63  motion_62  1163 non-null   float64
 64  motion_63  1163 non-null   float64
dtypes: float64(64), int64(1)
memory usage: 590.7 KB
None
--------------------------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4650 entries, 0 to 4649
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      4650 non-null   int64
 1   pose    4650 non-null   int64
dtypes: int64(2)
memory usage: 72.8 KB
None
--------------------------------------------------------------------------------

### describe

In [24]:
print(X_train.describe())
print("-"*80)
print(X_test.describe())
print("-"*80)
print(y_train.describe())
print("-"*80)

                ID     motion_0     motion_1     motion_2     motion_3  \
count  4650.000000  4650.000000  4650.000000  4650.000000  4650.000000
mean   2888.036989    -0.261720    -0.665806    -0.773118    -0.787527
std    1673.571941    21.637217     9.004178     4.810937     8.108536
min       0.000000  -116.000000   -99.000000   -27.000000   -73.000000
25%    1436.250000   -11.000000    -3.000000    -3.000000    -4.000000
50%    2881.500000    -2.000000    -1.000000    -1.000000    -1.000000
75%    4327.500000     8.000000     2.000000     1.000000     3.000000
max    5810.000000   111.000000    90.000000    34.000000    43.000000

          motion_4     motion_5     motion_6     motion_7     motion_8  ...  \
count  4650.000000  4650.000000  4650.000000  4650.000000  4650.000000  ...
mean     -0.345376    -0.266452    -1.383226    -0.664946    -0.139785  ...
std      18.286323    20.858478    34.197266    17.697416    21.263171  ...
min     -90.000000   -95.000000  -128.000000  -128.000000  -110.000000  ...
25%     -10.000000   -11.000000    -6.000000    -8.000000   -11.000000  ...
50%       0.000000    -1.000000    -1.000000    -1.000000    -1.000000  ...
75%      10.000000    11.000000     3.000000     6.000000     8.000000  ...
max      81.000000   105.000000   127.000000   112.000000   127.000000  ...

         motion_54    motion_55    motion_56    motion_57    motion_58  \
count  4650.000000  4650.000000  4650.000000  4650.000000  4650.000000
mean     -2.466667    -1.077849    -1.105161    -0.657204    -0.772043
std      34.755376    17.524489    20.990875     8.969699     4.763189
min    -128.000000  -128.000000  -107.000000  -128.000000   -46.000000
25%      -7.000000    -8.000000   -12.000000    -4.000000    -3.000000
50%      -1.000000    -1.000000    -2.000000    -1.000000    -1.000000
75%       3.000000     6.000000     7.000000     2.000000     2.000000
max     127.000000   111.000000   127.000000   105.000000    28.000000

         motion_59    motion_60    motion_61    motion_62    motion_63
count  4650.000000  4650.000000  4650.000000  4650.000000  4650.000000
mean     -0.639785    -0.054839    -0.341075    -1.820430    -0.751398
std       8.098629    18.562673    20.456560    34.662528    17.713153
min     -62.000000  -103.000000  -121.000000  -128.000000  -104.000000
25%      -4.000000   -10.000000   -11.000000    -6.000000    -8.000000
50%      -1.000000     0.000000     0.000000    -1.000000    -1.000000
75%       3.000000    10.000000    10.000000     3.000000     6.000000
max      51.000000   110.000000   102.000000   127.000000   114.000000

[8 rows x 65 columns]
--------------------------------------------------------------------------------
                ID     motion_0     motion_1     motion_2     motion_3  \
count  1163.000000  1163.000000  1163.000000  1163.000000  1163.000000
mean   2977.821152     0.042132    -0.771281    -0.889080    -1.182287
std    1695.465574    22.244087     7.940135     4.947982     8.675115
min       1.000000   -72.000000   -70.000000   -27.000000   -59.000000
25%    1516.000000   -12.000000    -4.000000    -3.000000    -4.000000
50%    3026.000000    -1.000000    -1.000000    -1.000000    -1.000000
75%    4463.000000     8.000000     2.000000     2.000000     2.000000
max    5812.000000   111.000000    44.000000    27.000000    31.000000

          motion_4     motion_5     motion_6     motion_7     motion_8  ...  \
count  1163.000000  1163.000000  1163.000000  1163.000000  1163.000000  ...
mean     -0.715391    -0.864144    -1.459157    -0.483233     0.257954  ...
std      19.069508    21.602068    35.362480    17.620117    22.454556  ...
min     -90.000000   -95.000000  -128.000000  -107.000000   -87.000000  ...
25%     -11.000000   -12.000000    -8.500000    -8.000000   -11.000000  ...
50%      -1.000000    -1.000000    -1.000000    -1.000000    -1.000000  ...
75%      10.000000    11.000000     3.000000     6.000000     8.000000  ...
max      71.000000    84.000000   127.000000    79.000000    97.000000  ...

         motion_54    motion_55    motion_56    motion_57    motion_58  \
count  1163.000000  1163.000000  1163.000000  1163.000000  1163.000000
mean     -0.565778    -0.039553    -1.192605    -0.749785    -0.750645
std      34.623817    18.239329    22.065090     9.462590     4.759237
min    -128.000000  -128.000000  -107.000000  -128.000000   -29.000000
25%      -7.000000    -8.000000   -12.000000    -4.000000    -3.000000
50%      -1.000000     0.000000    -2.000000    -1.000000    -1.000000
75%       4.000000     7.000000     7.000000     2.000000     2.000000
max     127.000000   111.000000    96.000000    61.000000    21.000000

         motion_59    motion_60    motion_61    motion_62    motion_63
count  1163.000000  1163.000000  1163.000000  1163.000000  1163.000000
mean     -0.625107     0.171109     0.358555    -2.397248    -0.938951
std       8.587834    17.958332    19.534855    35.654448    18.204959
min     -62.000000   -80.000000   -84.000000  -128.000000   -93.000000
25%      -4.000000    -9.000000   -10.000000    -8.500000    -8.000000
50%       0.000000     0.000000    -1.000000    -1.000000    -1.000000
75%       3.000000     9.000000    10.000000     3.000000     6.000000
max      51.000000   110.000000    87.000000   127.000000   114.000000

[8 rows x 65 columns]
--------------------------------------------------------------------------------
                ID         pose
count  4650.000000  4650.000000
mean   2888.036989     0.499355
std    1673.571941     0.500053
min       0.000000     0.000000
25%    1436.250000     0.000000
50%    2881.500000     0.000000
75%    4327.500000     1.000000
max    5810.000000     1.000000
--------------------------------------------------------------------------------

### isna

In [25]:
print(X_train.isna().sum().sum())
print("-"*80)
print(X_test.isna().sum().sum())
print("-"*80)
print(y_train.isna().sum().sum())
print("-"*80)

0
--------------------------------------------------------------------------------
0
--------------------------------------------------------------------------------
0
--------------------------------------------------------------------------------

In [26]:
X_train = X_train.drop(columns = "ID")
X_test = X_test.drop(columns="ID")
y_train_ID = y_train.pop('ID')

### 표준화

In [21]:
# from sklearn.preprocessing import MinMaxScaler
# Scaler = MinMaxScaler()
# X_train = Scaler.fit_transform(X_train)

,motion_0,motion_1,motion_2,motion_3,motion_4,motion_5,motion_6,motion_7,motion_8,motion_9,...,motion_54,motion_55,motion_56,motion_57,motion_58,motion_59,motion_60,motion_61,motion_62,motion_63
0,1.0,-2.0,-1.0,4.0,-5.0,-4.0,1.0,0.0,-15.0,-3.0,...,0.0,-1.0,-13.0,-3.0,1.0,-1.0,-32.0,-22.0,-2.0,-3.0
1,20.0,0.0,0.0,1.0,5.0,6.0,-52.0,18.0,15.0,-5.0,...,-70.0,-55.0,-38.0,-14.0,-12.0,-8.0,-34.0,-63.0,-87.0,-77.0
2,1.0,-1.0,1.0,4.0,-5.0,-8.0,1.0,-3.0,-14.0,-5.0,...,1.0,12.0,-25.0,0.0,0.0,3.0,2.0,-27.0,1.0,0.0
3,13.0,2.0,1.0,-3.0,1.0,3.0,28.0,3.0,12.0,1.0,...,0.0,-21.0,-17.0,-2.0,0.0,-4.0,-17.0,-21.0,-21.0,25.0
4,-2.0,-7.0,-4.0,-8.0,16.0,44.0,1.0,3.0,-16.0,2.0,...,-1.0,2.0,-1.0,1.0,4.0,4.0,-17.0,-38.0,-3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4645,3.0,-3.0,-4.0,-9.0,-10.0,7.0,-3.0,-5.0,-6.0,-5.0,...,-2.0,-2.0,-15.0,-6.0,0.0,0.0,22.0,23.0,-4.0,-3.0
4646,71.0,19.0,-18.0,-39.0,-26.0,-29.0,-28.0,0.0,11.0,-33.0,...,-54.0,-6.0,-34.0,-29.0,-8.0,-12.0,2.0,-7.0,55.0,19.0
4647,-10.0,-7.0,-2.0,-6.0,-1.0,9.0,-76.0,-17.0,40.0,5.0,...,91.0,30.0,24.0,-3.0,1.0,8.0,0.0,-7.0,-76.0,28.0
4648,6.0,4.0,5.0,4.0,-11.0,-2.0,11.0,11.0,-19.0,-3.0,...,-7.0,-14.0,-67.0,-3.0,-4.0,-2.0,-5.0,7.0,14.0,22.0
4649,-2.0,0.0,0.0,-1.0,4.0,11.0,-2.0,-19.0,13.0,-1.0,...,-5.0,-2.0,-10.0,4.0,0.0,-3.0,-12.0,-22.0,-4.0,5.0

### 원핫인코딩

### 검증용 데이터 분리

In [29]:
from sklearn.model_selection import train_test_split
X_tr, X_ts, y_tr, y_ts = train_test_split(X_train, y_train, test_size=0.3)

## 모델링

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
modelRF = RandomForestClassifier()
modelRF.fit(X_tr, y_tr) # 모델 학습
modelRF.score(X_ts, y_ts) # 1차 모델 성능

C:\Users\inseo\AppData\Local\Temp\ipykernel_16068\2788905706.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  modelRF.fit(X_tr, y_tr) # 모델 학습

0.992831541218638

In [33]:
y_pred = modelRF.predict(X_ts)
y_pred

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [35]:
pred = modelRF.predict(X_test)
pred

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [38]:
ans = pd.DataFrame({
    'pred' : pred
})

ans.to_csv('result.csv')